### ISSUE TITLE
Unresolved imports and functions

### ISSUE THREAD

**Issue by DanielTheProgrammer** [shankarp8/knowledge_distillation#2]
This project looks awesome, but there's some conflicts. where do you implement those functions(red marked)? 
<img width="1083" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/6bd5a54f-d39d-43c7-998b-50d65b70201d">

**Comment by shankarp8** [comment]
Hi, thanks very much for pointing this out! A number of those functions are redundant now, so I removed them. Please let me know if you have any other questions!

**Comment by DanielTheProgrammer** [comment]
Thank you so much for the quick response, unfortunately there's still problems:
<img width="417" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/6b1c2574-526c-4f0a-a0ea-03e78c336267">
<img width="621" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/848489a6-3a35-4c3b-a45c-9ed1858c481f">
<img width="534" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/6c9ed4e4-bf7b-48e2-aa26-68afdef810e2">
<img width="423" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/949ece82-161e-4964-ab5f-dcc24ac02855">
<img width="267" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/a8a21e1e-2982-4778-9684-d308cf9e029f">
<img width="922" alt="image" src="https://github.com/shankarp8/knowledge_distillation/assets/55857406/5c9bac8c-4959-4f56-9e5d-680d74e8c0f6">

**Comment by shankarp8** [comment]
Thanks again! I fixed these issues, and I confirmed that everything runs properly now. I left the mend and rome calls there because I will update this repo for compatibility with MEND, ROME, and MEMIT in the future; for now, even though they are not implemented here yet, the code will still work as long as you don't set the editing method to 'mend', 'rome', or 'memit'.
