### ISSUE TITLE
Generation of Augmented Probes

### ISSUE THREAD

**Issue by duygunuryldz** [shankarp8/knowledge_distillation#3]
This is a very nice and inspiring project. However, I could not find how augmented probes for entity inferences dataset is generated. Could you point out where is it in the repository? Or if not added to the repo, is it possible to share that code?

**Comment by shankarp8** [comment]
Apologies for the huge delay in my response, and thank you for your interest in the project! The augmented probes for both entity inferences and ECBD are generated using the GPT-3.5 API. If you would like, I can share the code, but it is a fairly straightforward API call.
