### ISSUE TITLE
Entities are independently updated and evaluated from each other?

### ISSUE THREAD

**Issue by Alice1998** [shankarp8/knowledge_distillation#5]
Thanks for this work.

I would like to confirm the implementation in run_edit.py, function run_edit_ecbd:

```python
model_ft = apply_batched_ft_distill_gpt(model_raw=model_raw, train_params=train_params, teacher=teacher, tokenizer=tokenizer, contexts=contexts, 
                                            unmasked_probe_set=unmasked_probe_set, ent_strs=ent_strs, device=device, after_ent_span=after_entity_span, 
                                            specificity_batches=specificity_batches, dataset_name=dataset_name)
```

Is `model_ft` always generated based on `model_raw` for each different entity, rather than being updated based on the previous `model_ft`? This means that each entity is updated and evaluated independently, rather than cumulatively updating all of them and then reviewing the updated model performance.

**Comment by shankarp8** [comment]
Apologies for the delay in my response, and thank you for your interest! Yes, model_ft is generated based on the raw model each time. Generally, in the default model editing scenario, we update the base model for only one entity and then evaluate the performance/specificity of the resulting model. 

With that being said, in our paper we investigate updating the model with up to 150 entities at once as well.
